---
os: linux
dist: xenial
language: node_js
node_js:
  - lts/*

addons:
  ssh_known_hosts: beta.tygr.info
  chrome: stable

# SSH Setup
before_deploy:
  - openssl aes-256-cbc
    -K $encrypted_db2095f63ba3_key
    -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc
    -out /tmp/deploy_rsa
    -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

jobs:
  include:
    - stage: quality
      script: npm run lint:check
    - script: npm run prettier:check

    - stage: test
      script:
        - HTTP_SERVER=true npm run build
        - npm test
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - path=/reports/${TRAVIS_PULL_REQUEST_SLUG-$TRAVIS_BRANCH}
          - rsync --recursive --delete reports tygr@beta.tygr.info:tygr$path/
          - echo build-report.html and test-report.html saved to https://beta.tygr.info$path
          - echo They will be preserved for 2 weeks

    - stage: deploy
      if: branch = master
      script: npm run build
      deploy:
        skip_cleanup: true
        provider: script
        script: rsync --recursive --delete dist tygr@beta.tygr.info:tygr
