---
os: linux
dist: xenial
language: node_js
node_js:
  - lts/*

addons:
  ssh_known_hosts: beta.tygr.info
  chrome: stable

# SSH Setup
before_deploy:
  - openssl aes-256-cbc
    -K $encrypted_db2095f63ba3_key
    -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc
    -out /tmp/deploy_rsa
    -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  allow_failures:
    - stage: test
      if: branch != master

  include:
    - stage: test
      script: npm run lint:check
    - script: npm run prettier:check
    - script:
        - HTTP_SERVER=true npm run build
        - npm test
      deploy:
        edge: true
        provider: script
        script: bash test-deploy.sh

    - stage: deploy
      script: npm run build
      deploy:
        edge: true
        provider: script
        script: bash web-deploy.sh
