---
language: node_js
node_js:
  - lts/*
jobs:
  include:
    - stage: quality
      script: npm run lint:check
    - script: npm run prettier:check
    - stage: build
      script: npm run build
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
