os: linux
dist: xenial
language: node_js
node_js:
  - lts/*

# SSH Setup
addons:
  ssh_known_hosts: cronpush.tygr.info
before_deploy:
  - openssl aes-256-cbc
    -K $encrypted_db2095f63ba3_key
    -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc
    -out /tmp/deploy_rsa
    -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

jobs:
  include:
    - stage: quality
      script: npm run lint:check
    - script: npm run prettier:check

    - stage: build
      script: npm run build
      deploy:
        on:
          branch: master
        cleanup: false
        provider: script
        script: rsync --recursive --delete $TRAVIS_BUILD_DIR/dist tygr@cronpush.tygr.info:tygr
