os: linux
dist: xenial
language: node_js
node_js:
  - lts/*

# SSH Setup
addons:
  ssh_known_hosts: cronpush.tygr.info
before_deploy:
  - openssl aes-256-cbc
    -K $encrypted_db2095f63ba3_key
    -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc
    -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

script:
  - npm run lint:check
  - npm run prettier:check
  - npm run build

deploy:
  provider: script
  script: rsync -rsh ssh --recursive --delete dist tygr@cronpush.tygr.info:tygr
  on:
    branch: master
