---
os: linux
dist: xenial
language: node_js
node_js:
  - lts/*

addons:
  ssh_known_hosts: beta.tygr.info
  chrome: stable

# SSH Setup
before_script:
  - openssl aes-256-cbc
    -K $encrypted_db2095f63ba3_key
    -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc
    -out /tmp/deploy_rsa
    -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

jobs:
  include:
    - stage: test
      script: npm run quality:check
    - env: NODE_ENV=test HOST=beta.tygr.info
      script:
        - npm run build
        - npm test
      after_script: bash test-deploy.sh

    - stage: deploy
      env: NODE_ENV=production HOST=beta.tygr.info
      if: branch = master
      script:
        - npm run build
        - bash web-deploy.sh
